# Generated by Django 5.0.14 on 2026-02-23 23:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movimientos_Cartera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('CARGO', 'Cargo'), ('INGRESO', 'Ingreso'), ('PAGO', 'Pago'), ('AJUSTE_SUMA', 'Ajuste (Suma)'), ('AJUSTE_RESTA', 'Ajuste (Resta)')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
