# Generated by Django 5.0.14 on 2026-02-23 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cartera', '0001_initial'),
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientos_cartera',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturas.facturas'),
        ),
        migrations.AddField(
            model_name='movimientos_cartera',
            name='fecha_pago_instancia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='facturas.facturasfechasdepago'),
        ),
    ]
