# Generated by Django 5.0.14 on 2026-02-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='plan',
            field=models.CharField(blank=True, choices=[('BASICO', 'Plan Básico'), ('PRO', 'Plan Pro')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='plan_pendiente',
            field=models.CharField(blank=True, choices=[('BASICO', 'Plan Básico'), ('PRO', 'Plan Pro')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='precio_mensual',
            field=models.DecimalField(decimal_places=2, default=199.0, max_digits=10),
        ),
    ]
