# Generated by Django 5.0.14 on 2026-02-24 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0003_add_plan_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suscripcion',
            name='plan_pendiente',
        ),
    ]
