# Generated by Django 5.0.14 on 2026-02-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0004_remove_plan_pendiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='pending_plan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='pending_plan_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='stripe_schedule_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
