# Generated by Django 5.0.14 on 2026-02-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=200, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('ABONADO', 'Abonado')], default='PENDIENTE', max_length=20)),
                ('tipo', models.CharField(choices=[('FACTURA', 'Factura'), ('REMISION', 'Remision'), ('GASTOS_GENERALES', 'Gastos Generales')], default='FACTURA', max_length=20)),
                ('cuenta_override', models.CharField(choices=[('AUTO', 'Auto (según tipo)'), ('PROVEEDOR', 'Cuenta del Proveedor'), ('MAESTRA', 'Cuenta Maestra')], default='AUTO', help_text='AUTO = según tipo de factura. Puedes forzar una cuenta específica.', max_length=20, verbose_name='Cuenta a mostrar')),
            ],
        ),
        migrations.CreateModel(
            name='FacturasFechasDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_por_pagar', models.DateField()),
                ('monto_por_pagar', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
