# Generated by Django 5.0.14 on 2026-02-23 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturas', '0001_initial'),
        ('proveedores', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organizacion'),
        ),
        migrations.AddField(
            model_name='facturas',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedores'),
        ),
        migrations.AddField(
            model_name='facturasfechasdepago',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.facturas'),
        ),
    ]
