# Generated by Django 5.0.14 on 2026-02-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='cuenta_override',
            field=models.CharField(choices=[('PROVEEDOR', 'Cuenta del Proveedor'), ('MAESTRA', 'Cuenta Maestra')], default='PROVEEDOR', help_text='Elige qué cuenta bancaria se muestra en el PDF y en el detalle del día.', max_length=20, verbose_name='Cuenta a mostrar'),
        ),
    ]
